FROM node:lts-buster

# ENV http_proxy=http://round.net.kajima.co.jp:8080
# ENV https_proxy=http://round.net.kajima.co.jp:8080
# ENV HTTP_PROXY=http://round.net.kajima.co.jp:8080
# ENV HTTPS_PROXY=http://round.net.kajima.co.jp:8080

# RUN npm config set proxy http://round.net.kajima.co.jp:8080
# RUN npm config set https-proxy http://round.net.kajima.co.jp:8080

RUN npm install -g @vue/cli